#!/usr/bin/env python3
"""
run_pipeline.py -- end-to-end ETL for the ISA swim-results project.

    extract (PDF -> CSV)  ->  load staging  ->  transform to core  ->  verify

The canonical target is PostgreSQL (sql/01_schema.sql, sql/03_transform.sql).
This runner executes the very same SQL against an embedded DuckDB database so
the whole pipeline is reproducible with zero server setup; a tiny shim removes
PostgreSQL's IDENTITY clause (the loader supplies surrogate ids explicitly, so
the SQL is otherwise identical on both engines).

Usage:
    python3 src/run_pipeline.py            # uses default sample paths
    python3 src/run_pipeline.py --db build/isa.duckdb
"""
from __future__ import annotations
import argparse, os, re, subprocess, sys, glob
import duckdb

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SAMPLE_DIR = os.path.join(ROOT, "samples")  # bundled ISA source PDFs


def find(pattern):
    hits = [f for f in glob.glob(os.path.join(SAMPLE_DIR, "*.pdf"))
            if pattern in os.path.basename(f)]
    if not hits:
        sys.exit(f"!! sample PDF not found for pattern {pattern!r} in {SAMPLE_DIR}")
    return hits[0]


def split_statements(sql: str):
    # drop line comments, then split on semicolons (no ';' appears in our
    # string literals or regexes, so this is safe for these scripts)
    no_comments = "\n".join(l for l in sql.splitlines()
                            if not l.strip().startswith("--"))
    return [s.strip() for s in no_comments.split(";") if s.strip()]


def to_duckdb(ddl: str) -> str:
    return ddl.replace("GENERATED BY DEFAULT AS IDENTITY", "")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=os.path.join(ROOT, "build", "isa.duckdb"))
    ap.add_argument("--results", default=None)
    ap.add_argument("--startlist", default=None)
    args = ap.parse_args()

    results_pdf = args.results or find("results_youth")
    startlist_pdf = args.startlist or find("startlist")
    interim = os.path.join(ROOT, "data", "interim")
    results_csv = os.path.join(interim, "results.csv")
    startlist_csv = os.path.join(interim, "startlist.csv")

    # 1) EXTRACT ---------------------------------------------------------
    print("== 1. extract ==")
    subprocess.run([sys.executable, os.path.join(HERE, "extract_results.py"),
                    results_pdf, "-o", results_csv], check=True)
    subprocess.run([sys.executable, os.path.join(HERE, "extract_startlist.py"),
                    startlist_pdf, "-o", startlist_csv], check=True)

    # 2) fresh database + schema ----------------------------------------
    print("\n== 2. schema ==")
    os.makedirs(os.path.dirname(args.db), exist_ok=True)
    if os.path.exists(args.db):
        os.remove(args.db)
    con = duckdb.connect(args.db)
    schema = open(os.path.join(ROOT, "sql", "01_schema.sql"), encoding="utf-8").read()
    for stmt in split_statements(to_duckdb(schema)):
        con.execute(stmt)
    print("   schema applied (tables + constraints + indexes)")

    # 3) LOAD staging ----------------------------------------------------
    print("\n== 3. load staging ==")
    con.execute("INSERT INTO stg_results SELECT * FROM "
                "read_csv(?, header=true, all_varchar=true)", [results_csv])
    con.execute("INSERT INTO stg_startlist SELECT * FROM "
                "read_csv(?, header=true, all_varchar=true)", [startlist_csv])
    print("   stg_results  :", con.execute("SELECT count(*) FROM stg_results").fetchone()[0])
    print("   stg_startlist:", con.execute("SELECT count(*) FROM stg_startlist").fetchone()[0])

    # 4) TRANSFORM -------------------------------------------------------
    print("\n== 4. transform (integrate + resolve) ==")
    transform = open(os.path.join(ROOT, "sql", "03_transform.sql"), encoding="utf-8").read()
    for stmt in split_statements(to_duckdb(transform)):
        con.execute(stmt)
    print("   core tables populated")

    # 5) VERIFY ----------------------------------------------------------
    print("\n== 5. verify ==")
    def q(sql):
        return con.execute(sql).fetchone()[0]

    counts = {t: q(f"SELECT count(*) FROM {t}") for t in
              ["club", "club_name_variant", "swimmer", "competition",
               "event", "heat", "entry", "result"]}
    for t, n in counts.items():
        print(f"   {t:18} {n}")

    print(f"\n   name variants -> canonical clubs : "
          f"{counts['club_name_variant']} spellings -> {counts['club']} clubs")
    print(f"   swims collapsed to swimmers    : "
          f"{q('SELECT count(*) FROM stg_results')} -> {counts['swimmer']} swimmers")

    timed = q("SELECT count(*) FROM result WHERE final_time_ms IS NOT NULL")
    statused = q("SELECT count(*) FROM result WHERE status IS NOT NULL")
    print(f"   results timed / statused       : {timed} / {statused}")

    # referential-integrity smoke tests (must all be 0)
    orphans = {
        "entry->heat":  q("SELECT count(*) FROM entry e LEFT JOIN heat h USING(heat_id) WHERE h.heat_id IS NULL"),
        "entry->swimmer": q("SELECT count(*) FROM entry e LEFT JOIN swimmer s USING(swimmer_id) WHERE s.swimmer_id IS NULL"),
        "result->entry": q("SELECT count(*) FROM result r LEFT JOIN entry e USING(entry_id) WHERE e.entry_id IS NULL"),
    }
    print("   orphan FKs (want 0):", orphans)
    assert set(orphans.values()) == {0}, "referential integrity violated!"
    con.close()
    print("\nOK -> database at", args.db)


if __name__ == "__main__":
    main()
