-- =====================================================================
--  ISA Swim Results  --  relational schema (PostgreSQL 14+)
--  Data Management final project  --  Asaf Belilus, BGU, Spring 2026
-- ---------------------------------------------------------------------
--  Design goal: take TWO messy, single-relation PDF exports (English
--  results + Hebrew start list) and normalise them to BCNF so that every
--  fact is stored exactly once, with keys and constraints enforcing
--  integrity. Surrogate ids are GENERATED BY DEFAULT so the ETL loader
--  may supply explicit values (the DuckDB verification harness strips the
--  IDENTITY clause; PostgreSQL keeps it).
-- =====================================================================

-- ---------- 0. reference (lookup) tables --------------------------------
CREATE TABLE ref_stroke (
    stroke_code   TEXT PRIMARY KEY,           -- 'FR','BK','BR','FL','IM'
    name_en       TEXT NOT NULL UNIQUE,
    name_he       TEXT
);

-- ---------- 1. staging tables (raw ELT landing zone) --------------------
--  Loaded verbatim from the extractor CSVs; every column TEXT so that
--  dirty values (e.g. 'NT', 'DNF / SW 10.2', wrapped club names) land
--  without failing, then get cleaned by the transformation SQL.
CREATE TABLE stg_results (
    source_file TEXT, page TEXT, event_no TEXT, distance_m TEXT, stroke TEXT,
    gender TEXT, age_group TEXT, rank TEXT, heat TEXT, lane TEXT,
    last_name TEXT, first_name TEXT, birth_year TEXT, club_raw TEXT,
    result_raw TEXT, status TEXT, dsq_rule TEXT, time_ms TEXT, fina_score TEXT
);

CREATE TABLE stg_startlist (
    source_file TEXT, page TEXT, distance_m TEXT, stroke TEXT, gender TEXT,
    age_group TEXT, heat TEXT, lane TEXT, club_code TEXT, entry_time_raw TEXT,
    entry_time_ms TEXT, birth_year TEXT, last_name_he TEXT, first_name_he TEXT,
    club_he TEXT
);

-- ---------- 2. core dimension tables ------------------------------------

--  A club is identified by its FEDERATION CODE (from the start list) --
--  the one language-neutral, stable key. English + Hebrew names hang off it.
CREATE TABLE club (
    club_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    federation_code INTEGER NOT NULL UNIQUE,     -- ISA club id, e.g. 422
    name_en       TEXT,                          -- canonical English name
    name_he       TEXT                           -- canonical Hebrew name
);

--  Entity-resolution audit trail: every raw spelling we ever observed for
--  a club, and where it came from. This is what turns "34 messy strings"
--  into "24 clubs" auditable, not magic.
CREATE TABLE club_name_variant (
    variant_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id       INTEGER NOT NULL REFERENCES club(club_id),
    spelling      TEXT NOT NULL,
    lang          TEXT NOT NULL CHECK (lang IN ('en','he')),
    source        TEXT NOT NULL,                 -- 'results' | 'startlist'
    seen_count    INTEGER NOT NULL DEFAULT 1,
    UNIQUE (club_id, spelling, lang)
);

--  A swimmer, resolved across all their swims. Bilingual name captured
--  from the two sources via the (event,heat,lane) bridge.
CREATE TABLE swimmer (
    swimmer_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name_en  TEXT,
    first_name_en TEXT,
    last_name_he  TEXT,
    first_name_he TEXT,
    birth_year    INTEGER CHECK (birth_year BETWEEN 1930 AND 2020),  -- masters incl.
    club_id       INTEGER REFERENCES club(club_id),
    UNIQUE (last_name_en, first_name_en, birth_year, club_id)
);

-- ---------- 3. competition structure ------------------------------------
CREATE TABLE competition (
    competition_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_he       TEXT NOT NULL,
    name_en       TEXT,
    start_date    DATE,
    end_date      DATE,
    course        TEXT CHECK (course IN ('LCM','SCM','SCY')),  -- pool length
    city          TEXT,
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE event (
    event_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id INTEGER NOT NULL REFERENCES competition(competition_id),
    event_no       INTEGER,                      -- printed programme number
    distance_m     INTEGER NOT NULL
                   CHECK (distance_m IN (25,50,100,200,400,800,1500)),
    stroke_code    TEXT NOT NULL REFERENCES ref_stroke(stroke_code),
    gender         TEXT NOT NULL CHECK (gender IN ('Girls','Boys','Mixed')),
    age_group      INTEGER NOT NULL,
    round          TEXT NOT NULL DEFAULT 'prelim'
                   CHECK (round IN ('prelim','final','timed_final')),
    UNIQUE (competition_id, distance_m, stroke_code, gender, age_group, round)
);

CREATE TABLE heat (
    heat_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      INTEGER NOT NULL REFERENCES event(event_id),
    heat_no       INTEGER NOT NULL,
    scheduled_at  TIMESTAMP,
    UNIQUE (event_id, heat_no)
);

-- ---------- 4. facts: entry (seeded) and result (swum) ------------------
--  entry  = a lane assignment from the START LIST (may carry a seed time,
--           or NULL when the swimmer entered "NT" = no time).
--  result = the outcome from the RESULTS sheet. A result is EITHER a
--           finish time OR a status (DNS/DSQ/DNF/NS) -- never neither.
CREATE TABLE entry (
    entry_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heat_id       INTEGER NOT NULL REFERENCES heat(heat_id),
    swimmer_id    INTEGER NOT NULL REFERENCES swimmer(swimmer_id),
    lane          INTEGER NOT NULL,
    seed_time_ms  INTEGER CHECK (seed_time_ms IS NULL OR seed_time_ms > 0),
    UNIQUE (heat_id, lane)
);

CREATE TABLE result (
    result_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id      INTEGER NOT NULL UNIQUE REFERENCES entry(entry_id),
    place         INTEGER CHECK (place IS NULL OR place > 0),
    final_time_ms INTEGER CHECK (final_time_ms IS NULL OR final_time_ms > 0),
    status        TEXT CHECK (status IS NULL OR
                              status IN ('DNS','DSQ','DNF','NS','SCR','WD')),
    dsq_rule      TEXT,                          -- e.g. 'SW 4.4' (FINA rule)
    fina_points   INTEGER CHECK (fina_points IS NULL OR fina_points >= 0),
    -- a result must be exactly one of {timed, statused}: the missing-value rule
    CHECK ( (final_time_ms IS NOT NULL) OR (status IS NOT NULL) )
);

-- ---------- 5. indexes chosen for the analytical query workload ---------
--  (rationale documented in docs/schema-design.md; EXPLAIN demos in 05_*)
CREATE INDEX idx_swimmer_name   ON swimmer (last_name_en, first_name_en, birth_year);
CREATE INDEX idx_swimmer_club   ON swimmer (club_id);
CREATE INDEX idx_event_lookup   ON event   (distance_m, stroke_code, gender, age_group);
CREATE INDEX idx_heat_event     ON heat    (event_id);
CREATE INDEX idx_entry_swimmer  ON entry   (swimmer_id);
CREATE INDEX idx_entry_heat     ON entry   (heat_id);
CREATE INDEX idx_result_time    ON result  (final_time_ms);
CREATE INDEX idx_result_fina    ON result  (fina_points);
